export const TaskActionTypes = {
    SET_TASKS: 'SET_TASKS',
    ADD_TASK: 'ADD_TASK',
    REMOVE_TASK:'REMOVE_TASK',
    SET_STATUS_TODO:'SET_STATUS_TODO',
    SET_STATUS_DOING:'SET_STATUS_DOING',
    SET_STATUS_DONE:'SET_STATUS_DONE',
}