export const TaskActionTypes = {
    SET_TASKS: 'SET_TASKS',
    ADD_TASK: 'ADD_TASK',
    REMOVE_TASK:'REMOVE_TASK',
    SET_STATUS_DOWNGRADE:'SET_STATUS_DOWNGRADE',
    SET_STATUS_UPGRADE:'SET_STATUS_UPGRADE',
    UPDATE_TASK : 'UPDATE_TASK',
    GET_TASK_TO_UPDATE : 'GET_TASK_TO_UPDATE'
}